global:
  imageRegistry: hub.global.cloud.sap
  domain: cloud.sap

  # Defined via secrets.
  # region:
  # cluster:
  # clusterType:

  alerts:
    enabled: true
    prometheus: infra-collector

  aggregations:
    enabled: true
    prometheus: infra-collector

#  altas:
#     ironic:
#       enabled: false
#  arista_exporter:
#    enabled: true

rbac:
  create: true
  name: infra-monitoring-edit
  namespace: infra-monitoring
  role:
    kind: ClusterRole
    name: edit
  service_account:
    name: default
    namespace: infra-monitoring

prometheus_infra_collector:
  name: infra-collector
  enabled: true

  retentionTime: 15m
  scrapeInterval: "60s"

  additionalScrapeConfigs:
    name: infra-collector-additional-scrape-config
    key: scrape-config.yaml
  configMaps:
    - arista-sd
    - atlas-sd

  ingress:
    enabled: true
    host: prometheus-infra-collector

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi

  rbac:
    create: true

  serviceAccount:
    create: true

  # alertmanagers:
  #  - alertmanager.eu-de-1.cloud.sap
  #  - alertmanager.eu-nl-1.cloud.sap

cloudprober_exporter:
  enabled: false

netapp_exporter:
  enabled: false

netapp-perf-exporter:
  enabled: false

arista_sd:
  enabled: false

arista_exporter:
  enabled: false

atlas_sd:
  enabled: false 

apic_exporters:
  enabled: false

snmp_exporter:
  enabled: false

bios_exporter:
  enabled: false

apic_exporters:
  enabled: false

vcenter-exporters:
  enabled: false

thousandeyes_exporter:
  enabled: false

ipmi_exporter:
  enabled: false

vcenter_exporters:
  enabled: false

blackbox_exporter:
  enabled: false